# -*- coding: utf-8 -*-
"""linear_algebra_toolkit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBlidaagIq9VyzeNETnoTlPeSBid_KkK
"""

import numpy as np

rowsA=int(input("enter the number rows u want matrix A to have:"))
columnsA=int(input("enter the number of columns matrix A should have"))

rowsB=int(input("enter the number rows u want matrix B to have:"))
columnsB=int(input("enter the number of columns matrix B should have"))

MatrixA=np.zeros((rowsA,columnsA),dtype=int)
MatrixB=np.zeros((rowsB,columnsB),dtype=int)

for i in range(0,rowsA):
  for j in range(0,columnsA):
    MatrixA[i][j]=int(input(f"Enter A[{i}][{j}]: "))

for i in range(0,rowsB):
  for j in range(0,columnsB):
    MatrixB[i][j]=int(input(f"Enter B[{i}][{j}]: "))

Addition="Not possible"
Subtraction="Not possible"
dot_Multiplication="Not possible"

if rowsA==rowsB and columnsA==columnsB:
  Addition=np.add(MatrixA,MatrixB)
  Subtraction=np.subtract(MatrixA,MatrixB)

if columnsA==rowsB:
  dot_Multiplication=np.dot(MatrixA,MatrixB)

TransposeA=MatrixA.T
TransposeB=MatrixB.T

DeterminantA="det of A does not exist"
if rowsA==columnsA:
  DeterminantA=np.linalg.det(MatrixA)

DeterminantB="det of B does not exist"
if rowsB==columnsB:
  DeterminantB=np.linalg.det(MatrixB)


rankA=np.linalg.matrix_rank(MatrixA)
rankB=np.linalg.matrix_rank(MatrixB)

invA="does not exist"
if np.linalg.det(MatrixA)!=0:
  invA=np.linalg.inv(MatrixA)

invB="does not exist"
if np.linalg.det(MatrixB)!=0:
  invB=np.linalg.inv(MatrixB)

try:
  solve=np.linalg.solve(MatrixA,MatrixB)
except:
  solve="matrix cannot be solved"

while True:
   user_input=input("enter what operation u ant to perform\n1. Add Matrices\n2. Subtract Matrices\n3. Multiply Matrices\n4. Transpose\n5. Determinant\n6. Inverse\n7. Solve AX = B\n8. Rank\n9. Exit")

   match user_input:
      case "1":
        print("the addition of the matrix is ",Addition)
      case "2":
        print("the substraction of the matrix is ",Subtraction)
      case "3":
        print("the multiplication of the matrix is",dot_Multiplication)
      case "4":
        print("the transpose of the matrix A and B is ",TransposeA,TransposeB)
      case "5":
        print("the determinant of the matrix A and B is",DeterminantA,DeterminantB)
      case "6":
        print("the inverse of the matrix A and B is:",invA,invB)
      case "7":
        print("solution upon solving A and B is ",solve)
      case "8":
        print("rank of matrix A and B are",rankA,rankB)
      case "9":
        break
      case _:
        print("invalid input")